# ======================
# НАСТРОЙКИ СЕРВЕРА
# ======================
server:
  port: 8080
  servlet:
    context-path: /api           # Базовый путь для всех API-эндпоинтов
  compression:
    enabled: true                # Включить сжатие Gzip для ответов
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024      # Минимальный размер для сжатия (1KB)

# ======================
# НАСТРОЙКИ SPRING BOOT
# ======================
spring:
  # ----- Datasource (MySQL) -----
  datasource:
    url: jdbc:mysql://localhost:3306/CodeWiki?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 14061946
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: CodeWiki-Pool
      maximum-pool-size: 10       # Максимальное число соединений с БД
      connection-timeout: 30000   # 30 секунд

  # ----- JPA & Hibernate -----
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true                # Логировать SQL-запросы
    hibernate:
      ddl-auto: update            # Автоматическое обновление схемы БД (в prod заменить на 'validate')
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true          # Форматировать SQL в логах
        jdbc.batch_size: 30       # Оптимизация для bulk-операций
        order_inserts: true
        order_updates: true

  # ----- Кеширование -----
  cache:
    type: caffeine                # Использовать Caffeine Cache
    caffeine:
      spec: maximumSize=500,expireAfterWrite=10m  # Макс. 500 записей, срок жизни 10 минут

  # ----- MVC (Статика, загрузка файлов) -----
  mvc:
    static-path-pattern: /static/**  # Путь к статическим файлам
  servlet:
    multipart:
      max-file-size: 10MB         # Макс. размер загружаемого файла
      max-request-size: 10MB

  # ----- Безопасность (JWT) -----
  security:
    oauth2:
      client:
        registration:             # OAuth2 (опционально)
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_SECRET}
            scope: user:email

# ======================
# КАСТОМНЫЕ НАСТРОЙКИ
# ======================
codewiki:
  jwt:
    secret: "your-256-bit-secret-key-here"  # Ключ для подписи JWT (заменить в продакшене!)
    expiration-ms: 86400000                 # Срок жизни токена (24 часа)
  admin:
    default-username: admin                 # Логин первого админа
    default-password: admin123              # Пароль (заменить в продакшене!)
  articles:
    max-drafts-per-user: 20                 # Лимит черновиков на пользователя

# ======================
# ЛОГИРОВАНИЕ
# ======================
logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG                # Логировать SQL-запросы
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # Логировать параметры запросов
  file:
    name: logs/codewiki.log                 # Путь к лог-файлу
    max-size: 10MB
    max-history: 7                          # Хранить логи за 7 дней

# ======================
# Swagger (OpenAPI 3.0)
# ======================
springdoc:
  api-docs:
    path: /v3/api-docs                     # Путь к JSON-документации
  swagger-ui:
    path: /swagger-ui.html                 # Путь к Swagger UI
    tags-sorter: alpha                     # Сортировка тегов по алфавиту
    operations-sorter: alpha               # Сортировка методов по алфавиту